### ISSUE TITLE
Bitbucket doesn't notify when a commit is pushed to remote when using `${EVERYTHING_URL}`

### ISSUE THREAD

**Issue by mtakaki** [tomasbjerre/pull-request-notifier-for-bitbucket#138] opened 2016-07-29 17:13 UTC
The plugin is currently failing to notify a new commit pushed to the pull request when the variable `${EVERYTHING_URL}` is used. It works when I manually add the variables I'm interested in.

This is the stack trace I get (I've removed sensitive data). Please let me know if you the rest of the stack trace. I didn't add it because it seemed irrelevant.

```
2016-07-28 14:44:47,432 ERROR [http-nio-**-443-exec-69] @ZQJ7JRx884x397225x2 jbhrfs **** "GET /s/d41d8cd98f00b204e9800998ecf8427e-CDN/1547702738/3b31f4c/50/2.31/_/download/batch/se.bjurr.prnfs.pull-request-notifier-for-stash:resources/se.bjurr.prnfs.pull-request-notifier-for-stash:resources.css HTTP/1.1" b.c.a.condition.CanTagCondition error while fetching repository
org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
    at org.springframework.security.access.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:339) ~[spring-security-core-3.2.7.RELEASE.jar:3.2.7.RELEASE]
    at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26) ~[atlassian-plugins-core-4.1.8.jar:na]
    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
    at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) ~[na:na]
    at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) ~[na:na]
    at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) ~[na:na]
    at be.contribute.atlassian.condition.CanTagCondition.getRepository(CanTagCondition.java:106) [plugin.4052744825699145293.stash-tagging-support-1.5.4_1463762034896.jar:na]
    at be.contribute.atlassian.condition.CanTagCondition.extractRepository(CanTagCondition.java:81) [plugin.4052744825699145293.stash-tagging-support-1.5.4_1463762034896.jar:na]
    at be.contribute.atlassian.condition.CanTagCondition.hasPermission(CanTagCondition.java:34) [plugin.4052744825699145293.stash-tagging-support-1.5.4_1463762034896.jar:na]
    at com.atlassian.bitbucket.web.conditions.AbstractPermissionCondition.shouldDisplay(AbstractPermissionCondition.java:105) [bitbucket-web-common-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.web.fragments.AbstractClientWebFragmentModuleDescriptor$WebFragmentPageDataProvider.getContextMap(AbstractClientWebFragmentModuleDescriptor.java:544) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.web.fragments.RequestCacheClientPageDataHandler.getPageData(RequestCacheClientPageDataHandler.java:50) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.web.fragments.RequestCacheClientPageDataHandler.requirePageData(RequestCacheClientPageDataHandler.java:78) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.OsgiSafeProxyProvider$1.invoke(OsgiSafeProxyProvider.java:93) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.web.fragments.WebFragmentLocationModuleDescriptor.requirePageData(WebFragmentLocationModuleDescriptor.java:112) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.web.fragments.WebFragmentLocationModuleDescriptor.getDependencies(WebFragmentLocationModuleDescriptor.java:195) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.plugin.webresource.impl.config.Config.getWebResourcesWithoutCache(Config.java:544) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.Globals$1.create(Globals.java:49) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.Globals$1.create(Globals.java:46) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.support.ResettableLazyReferenceWithVersionCheck.get(ResettableLazyReferenceWithVersionCheck.java:23) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.Globals.getSnapshot(Globals.java:166) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.RequestCache.getSnapshot(RequestCache.java:131) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller.getBatchResources(Controller.java:159) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller$2.get(Controller.java:127) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller$2.get(Controller.java:124) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.helpers.ResourceServingHelpers$1.writeTo(ResourceServingHelpers.java:104) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller$6.write(Controller.java:362) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.cache.filecache.impl.PassThroughCache.cache(PassThroughCache.java:18) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller.sendCachedInProduction(Controller.java:359) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller.sendCached(Controller.java:322) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller.serveResources(Controller.java:262) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Controller.serveBatch(Controller.java:124) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Router$7.apply(Router.java:112) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.http.Router$7.apply(Router.java:103) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.support.http.BaseRouter.callHandler(BaseRouter.java:171) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.impl.support.http.BaseRouter.dispatch(BaseRouter.java:144) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.plugin.webresource.servlet.PluginResourceDownload.serveFile(PluginResourceDownload.java:65) [atlassian-plugins-webresource-3.5.29.jar:na]
    at com.atlassian.stash.internal.plugin.FileServerServlet.access$000(FileServerServlet.java:24) [bitbucket-platform-4.6.2.jar:na]
    at com.atlassian.stash.internal.plugin.FileServerServlet$1.perform(FileServerServlet.java:41) [bitbucket-platform-4.6.2.jar:na]
```

**Comment by tomasbjerre** [comment] 2016-07-29 18:13
Is there anything abotu "se.bjurr" in the log?
I dont think its that exception causing the problem.

**Comment by mtakaki** [comment] 2016-07-29 18:14
Not in the stack trace. Only thing I see with "se.bjurr" is this part in the beginning:

```
GET /s/d41d8cd98f00b204e9800998ecf8427e-CDN/1547702738/3b31f4c/50/2.31/_/download/batch/se.bjurr.prnfs.pull-request-notifier-for-stash:resources/se.bjurr.prnfs.pull-request-notifier-for-stash:resources.css HTTP/1.1" b.c.a.condition.CanTagCondition error while fetching repository
```

**Comment by tomasbjerre** [comment] 2016-07-29 23:08
What version of the plugin do you use?

In 2.32 I changed it so that the plugin sends a notification with the variables that can be resolved. If one cannot be resolved because of a crash, it will be logged, but the others will be rendered. Previous version has given up completely once one variable crashed on resolve.

So the issue is probably still there, but is less severe now.

**Comment by mtakaki** [comment] 2016-08-08 22:10
Sorry about the delay to answer you. We're using 2.34, actually.

**Comment by tomasbjerre** [comment] 2016-08-09 04:26
Ok. That cannot have been the cersion used when bug was found. I suspect that this is fixed in your current version.

https://marketplace.atlassian.com/plugins/se.bjurr.prnfs.pull-request-notifier-for-stash/versions

**Comment by tomasbjerre** [comment] 2016-08-12 15:34
Closing this one. It is probably solved.

**Closed by tomasbjerre** 2016-08-12 15:34 UTC
Labels: bug
